server:
  port: 9004
spring:
  application:
    name: project-C
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://xxx
    username: dev
    password: mko0PL<.;?
  cloud:
    nacos:
      discovery:
        server-addr: xxx #配置nacos地址
  sleuth:
    propagation:
      tag:
        whitelisted-keys:
          - transactiontrace-id
    propagation-keys:
      - transactiontrace-id
#打开全部监控端点
maagement:
  endpoints:
    web:
      exposure:
        include: '*'