server:
  port: 9003
spring:
  application:
    name: project-A
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://xxx
    username: dev
    password: xxx
  cloud:
    nacos:
      discovery:
        server-addr: xxx #配置nacos地址
  sleuth:
    propagation:
      tag:
        whitelisted-keys:
          - transaction-trace-id
    propagation-keys:
      - transaction-trace-id
#打开全部监控端点
maagement:
  endpoints:
    web:
      exposure:
        include: '*'